name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        python-version: ['3.12', '3.13']
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Install dependencies
        run: |
          uv sync
          uv sync --extra dev
      - name: Run tests
        run: uv run pytest tests/ -v --cov=src/arborist --cov-report=term-missing

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            ~/.cache/pre-commit
          key: ${{ runner.os }}-uv-precommit-${{ hashFiles('pyproject.toml', '.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-uv-precommit-
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Install dependencies
        run: |
          uv sync
          uv sync --extra dev
      - name: Make hook scripts executable
        run: chmod +x .github/hooks/*.py
      - name: Initialize pre-commit
        run: |
          uv run pre-commit install --install-hooks
          uv run pre-commit install --hook-type pre-push
          uv run pre-commit install --hook-type pre-commit
          uv run pre-commit install --hook-type commit-msg
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - name: Run pre-commit hooks
        run: |
          uv run pre-commit run --all-files --show-diff-on-failure
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "style: fix code style issues"
            git push
          fi
